version: '3.9'

services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
  server:
    container_name: paarre-backend
    ports:
      - 49160:49160
    depends_on:
      - mysql
    links:
      - mysql:mysql
    build:
      context: . .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
volumes:
  db-config:
  db-data:
